import { AuthError, AuthService } from "../../services/auth.js";
import { h, icon } from "../dom.js";
type Mode="login"|"register";type Success=(user:Awaited<ReturnType<AuthService["login"]>>,card:HTMLElement)=>void;
export function mountAuth(root:HTMLElement,auth:AuthService,onSuccess:Success):void{root.hidden=false;const artwork=h("img",{class:"hero-art",src:"assets/brand/hero-tony-lucky.png",alt:"Tony and Lucky listening to music",width:484,height:452,decoding:"async"});const note=(i:number)=>h("span",{class:`hero-note n${i}`},icon("music-note",24));const hero=h("section",{class:"auth-hero","aria-label":"Tony Luk Music"},h("span",{class:"hero-glow"}),h("span",{class:"hero-ring"}),note(1),note(2),note(3),note(4),h("span",{class:"hero-paw"},icon("paw",26)),artwork,h("div",{class:"hero-copy"},h("h1",{},"Music that walks beside you."),h("p",{},"Inspired by Tony & Lucky")));
 const tabs=h("div",{class:"auth-tabs",dataset:{mode:"login"},role:"tablist","aria-label":"Account access"});const loginTab=h("button",{class:"auth-tab",type:"button",role:"tab","aria-selected":"true","aria-controls":"auth-form",id:"tab-login"},"Sign in");const registerTab=h("button",{class:"auth-tab",type:"button",role:"tab","aria-selected":"false","aria-controls":"auth-form",id:"tab-register"},"Create account");tabs.append(h("span",{class:"auth-tab-indicator","aria-hidden":"true"}),loginTab,registerTab);
 const heading=h("h2",{class:"auth-heading",id:"auth-heading"},"Welcome back");const subtitle=h("p",{class:"auth-subtitle"},"Sign in to pick up where the music left off.");const fields=h("div",{class:"auth-fields"});const error=h("p",{class:"auth-form-error",role:"alert","aria-live":"polite"});const submit=h("button",{class:"auth-submit",type:"submit"},"Sign in");const form=h("form",{id:"auth-form",noValidate:true},fields,error,submit);const card=h("section",{class:"auth-card","aria-labelledby":"auth-heading"},tabs,heading,subtitle,form,h("p",{class:"auth-helper"},"Your account lives in this browser."));
 let mode:Mode="login",busy=false,showPassword=false;const values={name:"",email:"",password:""};const inputMap=new Map<string,HTMLInputElement>();const errors=new Map<string,HTMLElement>();
 const setField=(field:"name"|"email"|"password",label:string,type:string,autocomplete:string,placeholder:string)=>{const id=`auth-${field}`,err=h("span",{class:"auth-error",id:`${id}-error`,role:"alert"});errors.set(field,err);const input=h("input",{id,name:field,type,autocomplete,placeholder,value:values[field],"aria-describedby":`${id}-error`,required:true,onInput:(event:Event)=>{values[field]=(event.currentTarget as HTMLInputElement).value;clearError(field)}});inputMap.set(field,input);let control:HTMLElement=input;if(field==="password"){const toggle=h("button",{class:"password-toggle",type:"button","aria-pressed":"false",onClick:()=>{showPassword=!showPassword;input.type=showPassword?"text":"password";toggle.textContent=showPassword?"Hide":"Show";toggle.setAttribute("aria-pressed",String(showPassword))}},"Show");control=h("div",{class:"auth-password-wrap"},input,toggle)}return h("div",{class:"auth-field",dataset:{field}},h("label",{for:id},label),control,err)};
 const renderFields=()=>{fields.replaceChildren();if(mode==="register")fields.append(setField("name","Name","text","name","Your name"));fields.append(setField("email","Email address","email","email","you@example.com"),setField("password","Password","password",mode==="login"?"current-password":"new-password",mode==="login"?"Your password":"At least 8 characters"))};
 const clearError=(field:string)=>{const target=errors.get(field);target?.replaceChildren();inputMap.get(field)?.removeAttribute("aria-invalid")};
 const changeMode=(next:Mode)=>{if(busy)return;mode=next;tabs.dataset.mode=mode;loginTab.setAttribute("aria-selected",String(mode==="login"));registerTab.setAttribute("aria-selected",String(mode==="register"));heading.textContent=mode==="login"?"Welcome back":"Create your account";subtitle.textContent=mode==="login"?"Sign in to pick up where the music left off.":"A little space for all the songs you love.";submit.textContent=mode==="login"?"Sign in":"Create account";error.textContent="";renderFields();inputMap.get(mode==="register"?"name":"email")?.focus()};
 loginTab.addEventListener("click",()=>changeMode("login"));registerTab.addEventListener("click",()=>changeMode("register"));renderFields();
 form.addEventListener("submit",async event=>{event.preventDefault();if(busy)return;busy=true;submit.disabled=true;submit.replaceChildren(h("span",{class:"auth-spinner","aria-hidden":"true"}),"One moment");error.textContent="";try{const user=mode==="login"?await auth.login(values.email,values.password):await auth.register(values.name,values.email,values.password);card.classList.add("is-leaving");setTimeout(()=>onSuccess(user,card),270)}catch(cause){if(cause instanceof AuthError){const field=cause.field;if(field==="form")error.textContent=cause.message;else{const target=errors.get(field);if(target){target.textContent=cause.message;inputMap.get(field)?.setAttribute("aria-invalid","true");inputMap.get(field)?.focus()}}}else error.textContent="Something went wrong. Please try again.";busy=false;submit.disabled=false;submit.textContent=mode==="login"?"Sign in":"Create account"}});
 root.replaceChildren(h("main",{class:"auth-layout"},hero,card));inputMap.get("email")?.focus({preventScroll:true});
}
