import type { Song } from "../../core/song.js";
import { searchItunes, songFromItunes } from "../../services/itunes.js";
import { h, icon } from "../dom.js";
import { ACTIONS, store } from "../store.js";
import { toast } from "../toast.js";

export function openOpsSheet(mode: "first" | "last" | "insert" = "last", at = 0): void {
  const app = store; if (!app) return;
  const list = app.library.getActiveList(); if (!list) return;
  let position = Math.max(0, Math.min(at, list.size)); let selected: Song | null = null; let selectedSongs: Song[] = []; let timer: ReturnType<typeof setTimeout> | undefined;
  const overlay = h("div", { class: "ops-overlay", onClick: (event: Event) => { if (event.target === overlay) close(); } });
  const dialog = h("section", { class: "ops-sheet", role: "dialog", "aria-modal": "true", "aria-labelledby": "ops-title", tabindex: "-1" });
  const title = mode === "first" ? "Add to the beginning" : mode === "insert" ? "Insert at position" : "Add to the end";
  const heading = h("h2", { id: "ops-title" }, title); const query = h("input", { type: "search", placeholder: "Search songs", "aria-label": "Search songs" });
  const results = h("div", { class: "ops-results", "aria-live": "polite" }); const status = h("p", { class: "ops-status" }, "Search the iTunes catalog.");
  const tabs = h("div", { class: "ops-tabs" }); const searchTab = h("button", { type: "button", class: "is-active" }, icon("search", 18), " Search"); const uploadTab = h("button", { type: "button" }, icon("upload", 18), " Upload"); const linkTab = h("button", { type: "button" }, icon("link", 18), " Link"); tabs.append(searchTab, uploadTab, linkTab);
  const stepper = h("div", { class: "ops-stepper", hidden: mode !== "insert" }); const positionText = h("span", { class: "mono-label" }); const preview = h("div", { class: "insert-preview", hidden: mode !== "insert", "aria-label": "Insertion position preview" });
  const updatePosition = (): void => { positionText.textContent = `Position ${position + 1} of ${list.size + 1}`; const before = position > 0 ? list.nodeAt(position - 1)?.value.title ?? "" : "null"; const after = position < list.size ? list.nodeAt(position)?.value.title ?? "" : "null"; preview.replaceChildren(h("span", {}, before || "null"), h("b", {}, "← prev"), h("strong", {}, selected?.title ?? "New song"), h("b", {}, "next →"), h("span", {}, after || "null")); };
  const minus = h("button", { type: "button", "aria-label": "Move position earlier", onClick: () => { position = Math.max(0, position - 1); updatePosition(); refreshConfirm(); } }, "−");
  const plus = h("button", { type: "button", "aria-label": "Move position later", onClick: () => { position = Math.min(list.size, position + 1); updatePosition(); refreshConfirm(); } }, "+"); stepper.append(minus, positionText, plus); updatePosition();
  const confirm = h("button", { type: "button", class: "gold-button", disabled: true }, "Choose a song"); const closeButton = h("button", { type: "button", class: "icon-button", "aria-label": "Close", onClick: close }, icon("close"));
  dialog.append(h("div", { class: "ops-heading" }, heading, closeButton), tabs, stepper, preview, query, status, results, confirm); overlay.append(dialog); document.body.append(overlay);
  dialog.focus(); const prior = document.activeElement;
  function close(): void { overlay.remove(); if (prior instanceof HTMLElement) prior.focus(); if (timer) clearTimeout(timer); }
  const showUpload = (): void => { results.replaceChildren(); query.hidden = true; status.textContent = "Choose one or more audio files from your device."; const input = h("input", { type: "file", accept: "audio/*", multiple: true, "aria-label": "Choose audio files", onChange: async (event: Event) => { const files = Array.from((event.currentTarget as HTMLInputElement).files ?? []); selectedSongs = []; for (const file of files) { const song: Song = { id: `local:${crypto.randomUUID()}`, title: file.name.replace(/\.[^.]+$/, ""), fileName: file.name, fileSize: file.size, url: URL.createObjectURL(file), source: "local" }; await import("../../services/idb.js").then(({ storeBlob }) => storeBlob(song.id, file)); const audio = new Audio(song.url); audio.addEventListener("loadedmetadata", () => { song.duration = audio.duration; }, { once: true }); selectedSongs.push(song); } selected = selectedSongs[0] ?? null; confirm.disabled = selectedSongs.length === 0; confirm.textContent = selectedSongs.length ? `Add ${selectedSongs.length} file${selectedSongs.length === 1 ? "" : "s"}` : "Choose a song"; status.textContent = selectedSongs.map(song => song.fileName).join(" · ") || "Choose one or more audio files from your device."; } }); results.append(input); };
  const showLink = (): void => { results.replaceChildren(); query.hidden = true; status.textContent = "Paste a YouTube, Spotify, or direct audio link."; const input = h("input", { type: "url", placeholder: "https://…", "aria-label": "Music link" }); const resolve = h("button", { type: "button", class: "gold-button", onClick: async () => { try { const { classifyUrl } = await import("../../services/links.js"); const kind = classifyUrl(input.value); let song: Song | null = null; if (kind.kind === "youtube" && kind.videoId) { const meta = await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(input.value)}&format=json`).then(r => r.json()) as { title?: string; author_name?: string; thumbnail_url?: string }; song = { id: `youtube:${kind.videoId}`, title: meta.title ?? "YouTube track", artist: meta.author_name, url: input.value, videoId: kind.videoId, artworkUrl: meta.thumbnail_url, source: "youtube" }; } else if (kind.kind === "spotify" && kind.trackId) { const meta = await import("../../services/spotify.js").then(m => m.fetchSpotifyMeta(kind.trackId!)); song = { id: `spotify:${kind.trackId}`, title: meta.title || "Spotify track", url: input.value, artworkUrl: meta.thumbnail_url, spotifyUri: `spotify:track:${kind.trackId}`, source: "spotify" }; } else if (kind.kind === "audio") song = { id: `remote:${crypto.randomUUID()}`, title: new URL(input.value).pathname.split("/").pop() || "Audio track", url: input.value, source: "remote" }; if (!song) throw new Error("This link is not supported."); add(song); } catch (error) { status.textContent = error instanceof Error ? error.message : "Could not read this link."; } } }, "Use link"); results.append(input, resolve); };
  searchTab.addEventListener("click", () => { query.hidden = false; status.textContent = "Search the iTunes catalog."; results.replaceChildren(); query.focus(); }); uploadTab.addEventListener("click", showUpload); linkTab.addEventListener("click", showLink);
  query.addEventListener("input", () => { if (timer) clearTimeout(timer); const term = query.value.trim(); if (term.length < 2) { results.replaceChildren(); status.textContent = "Search the iTunes catalog."; return; } status.textContent = "Searching…"; timer = setTimeout(() => { void searchItunes(term, "all").then(items => { results.replaceChildren(); status.textContent = items.length ? "Choose a song to add." : "No songs found."; items.slice(0, 6).forEach(item => { const song = songFromItunes(item); const button = h("button", { type: "button", class: "ops-result", onClick: () => { selected = song; selectedSongs = [song]; confirm.disabled = false; confirm.textContent = mode === "insert" ? `Insert at position ${position + 1}` : "Add song"; updatePosition(); } }, h("img", { src: song.artworkUrl, alt: "", width: 44, height: 44 }), h("span", {}, h("strong", {}, song.title), h("small", {}, song.artist ?? ""))); results.append(button); }); }).catch(() => { status.textContent = "Search is unavailable. Try again."; }); }, 300); });
  function refreshConfirm(): void { if (mode === "insert" && selectedSongs.length) confirm.textContent = `Insert at position ${position + 1}`; }
  function add(song: Song): void { selected = song; selectedSongs = [song]; confirm.disabled = false; confirm.textContent = mode === "insert" ? `Insert at position ${position + 1}` : "Add song"; updatePosition(); }
  confirm.addEventListener("click", () => { if (!selectedSongs.length) return; const songs = selectedSongs; songs.forEach((song, index) => { if (mode === "first") { if (songs.length === 1) ACTIONS.addFirst(song); else ACTIONS.insertAt(index, song); } else if (mode === "insert") ACTIONS.insertAt(position + index, song); else ACTIONS.addLast(song); }); close(); toast({ message: mode === "insert" ? `Inserted “${songs[0]?.title ?? "songs"}” at position ${position + 1}` : `Added ${songs.length === 1 ? `“${songs[0]?.title ?? "song"}”` : `${songs.length} songs`} to the playlist` }); });
  overlay.addEventListener("keydown", (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key === "Tab") { const focusables = Array.from(dialog.querySelectorAll<HTMLElement>("button:not(:disabled),input:not([hidden])")); const first = focusables[0], last = focusables[focusables.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } });
}
