import type { Song, SongNode } from "../../core/song.js";
import { formatTime, h, icon } from "../dom.js";
import { observeReveals } from "../motion.js";
import { ACTIONS, on, store } from "../store.js";
import { toast } from "../toast.js";
import { mountChain } from "../components/chain.js";
import { openOpsSheet } from "../components/opsSheet.js";
import { songRow } from "../components/songRow.js";

export function mountPlaylistView(root: HTMLElement): void {
  const app = store!; const list = app.library.getActiveList()!; const page = h("section", { class: "playlist-page" });
  const cover = h("div", { class: "playlist-mosaic" }); const name = h("h1", { class: "playlist-name" }, app.library.getActiveName() ?? "My Playlist"); const meta = h("p", { class: "playlist-meta" });
  const chain = mountChain(list, node => { void ACTIONS.playNode(node); }); const chainWrap = h("section", { class: "playlist-chain-wrap", "aria-label": "Linked list visualization" }, h("div", { class: "section-head" }, h("h2", {}, "The Chain"), h("span", { class: "mono-label" }, "Doubly linked list")), chain);
  const operations = h("div", { class: "operations" }, h("span", { class: "mono-label" }, "List operations"));
  const addButton = (label: string, glyph: "plus" | "trash" | "prev" | "next", fn: () => void, extra = ""): HTMLButtonElement => h("button", { type: "button", class: `operation-button ${extra}`, onClick: fn }, icon(glyph, 18), label);
  operations.append(addButton("Add first", "plus", () => openOpsSheet("first")), addButton("Add last", "plus", () => openOpsSheet("last")), addButton("Insert at position", "plus", () => openOpsSheet("insert", Math.floor(list.size / 2))), addButton("Delete", "trash", () => { page.classList.toggle("delete-mode"); done.hidden = !page.classList.contains("delete-mode"); }), addButton("Previous", "prev", () => { void ACTIONS.prev(); }), addButton("Next", "next", () => { void ACTIONS.next(); }));
  const done = h("button", { type: "button", class: "delete-done", hidden: true, onClick: () => { page.classList.remove("delete-mode"); done.hidden = true; } }, "Done"); operations.append(done);
  const rows = h("div", { class: "song-rows", role: "list" }); const empty = h("div", { class: "playlist-empty" }, h("img", { src: "assets/brand/logo-stacked.png", alt: "", width: 192, height: 175 }), h("h2", {}, "This playlist is empty"), h("p", {}, "Add a song and watch the chain take shape."), h("div", { class: "empty-actions" }, h("button", { type: "button", class: "gold-button", onClick: () => openOpsSheet("last") }, "Search music"), h("button", { type: "button", onClick: () => openOpsSheet("first") }, "Add first song")));
  const keyedRows = new Map<string, HTMLElement>();
  const header = h("header", { class: "playlist-header" }, cover, h("div", {}, h("span", { class: "eyebrow mono-label" }, "YOUR PLAYLIST"), name, meta));
  page.append(header, chainWrap, operations, rows, empty); root.replaceChildren(page);
  const total = (): number => { let n = 0, node = list.head; while (node) { n += node.value.duration ?? 0; node = node.next; } return n; };
  const refreshHeader = (): void => { const fragment = document.createDocumentFragment(); let node = list.head; for (let i = 0; i < 4 && node; i++, node = node.next) fragment.append(h("img", { src: node.value.artworkUrl || "assets/brand/app-icon.png", alt: "", width: 82, height: 82, loading: "lazy", decoding: "async" })); cover.replaceChildren(fragment); const position = list.current ? list.indexOf(list.current) + 1 : 0; const where = position > 0 ? `now at position ${position} of ${list.size}` : "nothing playing yet"; meta.textContent = `${list.size} ${list.size === 1 ? "song" : "songs"} · ${formatTime(total())} total · ${where}`; empty.hidden = list.size > 0; rows.hidden = list.size === 0; };
  const remove = (node: SongNode): void => { const info = ACTIONS.deleteNode(node); toast({ message: `Removed “${info.song.title}”`, actionLabel: "Undo", onAction: () => { ACTIONS.undoDelete(info); renderRows(); } }); renderRows(); };
  const renderRows = (): void => { const old = Array.from(rows.children).filter((item): item is HTMLElement => item instanceof HTMLElement && item.classList.contains("song-row")); const positions = new Map(old.map(row => [row, row.getBoundingClientRect()])); const nextRows = new Map<string, HTMLElement>(); const fragment = document.createDocumentFragment(); let node = list.head; let index = 0; while (node) { const current = node; const insertAt = index + 1; let row = keyedRows.get(current.value.id); if (!row) row = songRow(current, index, remove, renderRows); row.dataset.index = String(index); row.querySelector<HTMLElement>(".row-position")!.textContent = String(index + 1).padStart(2, "0"); row.setAttribute("aria-label", `${index + 1}. ${current.value.title} by ${current.value.artist ?? "Unknown artist"}`); nextRows.set(current.value.id, row); fragment.append(row); fragment.append(h("button", { type: "button", class: "insert-gap", "aria-label": `Insert at position ${insertAt + 1}`, onClick: () => openOpsSheet("insert", insertAt) }, "+ insert here")); node = current.next; index++; } keyedRows.clear(); nextRows.forEach((row, id) => keyedRows.set(id, row)); rows.replaceChildren(fragment); nextRows.forEach(row => { const before = positions.get(row), after = row.getBoundingClientRect(); if (before && (before.left !== after.left || before.top !== after.top)) row.animate([{ transform: `translate(${before.left - after.left}px,${before.top - after.top}px)` }, { transform: "translate(0,0)" }], { duration: 360, easing: "cubic-bezier(.22,1,.36,1)" }); }); refreshHeader(); };
  const updateCurrent = (): void => { rows.querySelectorAll<HTMLElement>(".song-row").forEach(row => row.classList.toggle("is-active", row.dataset.songId === list.current?.value.id)); refreshHeader(); };
  renderRows(); observeReveals(page); on("library", renderRows); on("playback", updateCurrent);
}
