import { toast } from "../toast.js";
import type { Song } from "../../core/song.js";
import { searchItunes, songFromItunes } from "../../services/itunes.js";
import { searchYouTube, songFromYouTube } from "../../services/youtube.js";
import { searchSpotify, songFromSpotify, fetchSpotifyMeta } from "../../services/spotify.js";
import { classifyUrl } from "../../services/links.js";
import { searchArchive, resolveArchiveAudio } from "../../services/archive.js";
import { h, icon, formatTime } from "../dom.js";
import { ACTIONS, store } from "../store.js";
import { navigate } from "../router.js";
import { openOpsSheet } from "../components/opsSheet.js";

type Source = "catalog" | "youtube" | "spotify" | "free" | "link";
const sources: Array<[Source, string]> = [["catalog", "Catalog"], ["youtube", "YouTube"], ["spotify", "Spotify"], ["free", "Free (CC)"], ["link", "Paste link"]];
export function mountSearchView(root: HTMLElement): void {
  let source: Source = prefSource(); let chip: "all" | "artist" | "song" = "all"; let timer: ReturnType<typeof setTimeout> | undefined; let controller: AbortController | null = null; let queryValue = new URLSearchParams(location.hash.split("?")[1] ?? "").get("q") ?? "";
  const page = h("section", { class: "search-page search-view" }, h("span", { class: "eyebrow mono-label" }, "DISCOVER MUSIC"), h("h1", {}, "Find your next favorite"));
  const field = h("div", { class: "search-field" }, h("input", { type: "search", value: queryValue, placeholder: "Songs, artists, albums, or a link", "aria-label": "Search music" }), h("button", { type: "button", class: "icon-button search-clear", "aria-label": "Clear search", onClick: () => { input.value = ""; input.focus(); schedule(); } }, icon("close", 18)));
  const input = field.querySelector("input")!; const segments = h("div", { class: "source-segments", role: "tablist", "aria-label": "Search source" }); const chips = h("div", { class: "search-chips" }); const note = h("p", { class: "search-note" }); const status = h("div", { class: "search-state", "aria-live": "polite" }); const results = h("div", { class: "search-results search-view-results" });
  sources.forEach(([id, label]) => segments.append(h("button", { type: "button", role: "tab", "aria-selected": String(source === id), onClick: () => switchSource(id) }, label)));
  ["all", "song", "artist"].forEach((value) => chips.append(h("button", { type: "button", class: chip === value ? "is-active" : "", onClick: () => { chip = value as typeof chip; refreshChips(); schedule(true); } }, value === "all" ? "All" : value === "song" ? "Songs" : "Artists")));
  page.append(field, segments, chips, note, status, results); root.replaceChildren(page); input.focus();
  refreshSource(); if (queryValue) schedule();
  function switchSource(next: Source): void { if (source === next) return; source = next; controller?.abort(); if (timer) clearTimeout(timer); try { localStorage.setItem(`tlm.searchSource.${store!.user.id}`, source); } catch { /* Search still works when storage is unavailable. */ } refreshSource(); schedule(true); }
  function refreshSource(): void { segments.querySelectorAll("button").forEach((button, index) => button.setAttribute("aria-selected", String(sources[index]?.[0] === source))); chips.hidden = source !== "catalog"; note.textContent = source === "youtube" ? "Full songs via YouTube" : source === "free" ? "Creative Commons music from Internet Archive" : ""; note.hidden = !note.textContent; status.textContent = source === "link" ? "Paste a YouTube, Spotify, or direct audio link." : ""; }
  function refreshChips(): void { chips.querySelectorAll("button").forEach((button, index) => button.classList.toggle("is-active", ["all", "song", "artist"][index] === chip)); }
  input.addEventListener("input", () => { queryValue = input.value; schedule(); }); input.addEventListener("keydown", event => { if (event.key === "Escape") { input.value = ""; schedule(); } });
  function schedule(immediate = false): void { if (timer) clearTimeout(timer); controller?.abort(); results.replaceChildren(); status.textContent = ""; const term = input.value.trim(); if (!term) return; if (source === "link") { controller = new AbortController(); void renderLink(term, controller.signal); return; } if (term.length < 2) return; status.textContent = "Searching…"; results.replaceChildren(...Array.from({ length: 6 }, () => h("div", { class: "search-skeleton" }))); timer = setTimeout(() => { controller = new AbortController(); void run(term, controller.signal); }, immediate ? 0 : 350); }
  async function run(term: string, signal: AbortSignal): Promise<void> { try { if (source === "catalog") { const items = await searchItunes(term, chip, signal); if (chip === "artist") { renderArtists(items.map(songFromItunes)); } else renderSongs(items.map(songFromItunes), term); }
    else if (source === "youtube") { const items = await searchYouTube(term, signal); if (!signal.aborted) renderSongs(items.map(songFromYouTube), term); }
    else if (source === "spotify") { const response = await searchSpotify(term, signal); if (signal.aborted) return; if (!response.available) { results.replaceChildren(); status.replaceChildren(h("span", {}, "Spotify search needs server credentials. You can still paste any Spotify track link."), h("button", { type: "button", class: "gold-button", onClick: () => switchSource("link") }, "Paste link")); } else renderSongs(response.items.map(songFromSpotify), term); }
    else if (source === "free") await runArchive(term, signal);
  } catch (error) { if (signal.aborted) return; results.replaceChildren(); status.replaceChildren(h("span", {}, error instanceof Error ? error.message : "Search is unavailable."), h("button", { type: "button", onClick: () => schedule(true) }, "Retry")); } }
  function renderSongs(songs: Song[], term: string): void { results.replaceChildren(); status.textContent = songs.length ? "" : `No results for “${term}”`; songs.forEach(song => results.append(songResult(song))); }
  function renderArtists(songs: Song[]): void { results.replaceChildren(); const groups = new Map<string, Song[]>(); songs.forEach(song => { const name = song.artist ?? "Unknown artist"; groups.set(name, [...(groups.get(name) ?? []), song]); }); if (!groups.size) { status.textContent = `No results for “${input.value.trim()}”`; return; } status.textContent = ""; for (const [artist, tracks] of groups) results.append(h("section", { class: "artist-result" }, h("header", {}, h("img", { src: tracks[0]?.artworkUrl || "assets/brand/app-icon.png", alt: "", width: 56, height: 56, loading: "lazy", decoding: "async" }), h("h2", {}, artist), h("button", { type: "button", class: "gold-button", onClick: () => tracks.slice(0, 5).forEach(song => ACTIONS.addLast(song)) }, "Play top songs")), ...tracks.slice(0, 4).map(songResult))); }
  function songResult(song: Song): HTMLElement { const row = h("article", { class: "search-song-row" }, h("img", { src: song.artworkUrl || "assets/brand/app-icon.png", alt: "", width: 54, height: 54, loading: "lazy", decoding: "async" }), h("span", { class: "search-song-copy" }, h("strong", {}, song.title), h("small", {}, `${song.artist ?? "Unknown artist"}${song.album ? ` · ${song.album}` : ""}`)), h("span", { class: "source-badge" }, sourceBadge(song)), h("span", { class: "search-duration tabular-nums" }, formatTime(song.duration ?? 0)));
    const play = h("button", { type: "button", class: "icon-button", "aria-label": `Play ${song.title}`, onClick: () => { const list = store!.library.getActiveList(); let node = list?.head ?? null; while (node && node.value.id !== song.id) node = node.next; const index = store!.player.current && list ? list.indexOf(store!.player.current) + 1 : list?.size ?? 0; const target = node ?? ACTIONS.insertAt(Math.max(0, index), song); void ACTIONS.playNode(target); } }, icon("play", 18));
    row.append(play, h("button", { type: "button", class: "search-action", onClick: () => { ACTIONS.addFirst(song); toast({ message: `Added “${song.title}” at the beginning (addFirst)` }); } }, icon("plus", 16), "Add first"), h("button", { type: "button", class: "search-action", onClick: () => { ACTIONS.addLast(song); toast({ message: `Added “${song.title}” at the end (addLast)` }); } }, icon("plus", 16), "Add last"), h("button", { type: "button", class: "search-action", onClick: () => { const list = store!.library.getActiveList(); const at = list && store!.player.current ? list.indexOf(store!.player.current) + 1 : list?.size ?? 0; openOpsSheet("insert", Math.max(0, at), song); } }, icon("plus", 16), "Insert at…")); return row; }
  async function runArchive(term: string, signal: AbortSignal): Promise<void> { const items = await searchArchive(term, signal); results.replaceChildren(); status.textContent = items.length ? "Choose a result to resolve its audio file." : `No results for “${term}”`; items.forEach(item => { const song: Song = { id: `archive:${item.identifier}`, title: item.title ?? "Untitled recording", artist: item.creator ?? "Unknown artist", source: "remote", url: "" }; const row = h("article", { class: "search-song-row" }, h("span", { class: "archive-art" }, icon("paw", 20)), h("span", { class: "search-song-copy" }, h("strong", {}, song.title), h("small", {}, `${song.artist} · Internet Archive · CC`)), h("button", { type: "button", class: "gold-button", onClick: async () => { const button = row.querySelector("button")!; button.disabled = true; button.textContent = "Resolving…"; try { const audio = await resolveArchiveAudio(item.identifier, signal); song.url = audio.url; song.duration = audio.duration; const added = ACTIONS.addLast(song); void ACTIONS.playNode(added); button.textContent = "Added"; } catch (error) { button.disabled = false; button.textContent = error instanceof Error ? error.message : "Retry"; } } }, "Resolve & add")); results.append(row); }); }
  async function renderLink(value: string, signal: AbortSignal): Promise<void> { results.replaceChildren(); status.textContent = "Checking link…"; const classified = classifyUrl(value); try { let song: Song; if (classified.kind === "youtube" && classified.videoId) { const response = await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(value)}&format=json`, { signal }); if (!response.ok) throw new Error("Could not read YouTube track details."); const meta = await response.json() as { title?: string; author_name?: string; thumbnail_url?: string }; song = { id: `youtube:${classified.videoId}`, title: meta.title ?? "YouTube track", artist: meta.author_name, url: value, videoId: classified.videoId, artworkUrl: meta.thumbnail_url, source: "youtube" }; }
      else if (classified.kind === "spotify" && classified.trackId) { const meta = await fetchSpotifyMeta(classified.trackId); song = { id: `spotify:${classified.trackId}`, title: meta.title || "Spotify track", url: value, artworkUrl: meta.thumbnail_url, spotifyUri: `spotify:track:${classified.trackId}`, source: "spotify" }; }
      else if (classified.kind === "audio") song = { id: `remote:${crypto.randomUUID()}`, title: new URL(value).pathname.split("/").pop() || "Audio track", url: value, source: "remote" };
      else throw new Error(classified.kind === "unsupported" ? "This link type is not supported. Try YouTube, Spotify, or a direct audio URL." : "Enter a valid YouTube, Spotify, or audio link.");
      if (signal.aborted) return; status.textContent = "Track ready"; results.append(songResult(song));
    } catch (error) { if (!signal.aborted) status.textContent = error instanceof Error ? error.message : "Could not read this link."; } }
}
function sourceBadge(song: Song): string { return song.source === "itunes" ? "Preview 30s" : song.source === "youtube" ? "YouTube" : song.source === "spotify" ? "Spotify" : song.id.startsWith("archive:") ? "CC" : "Audio"; }
function prefSource(): Source { try { const value = localStorage.getItem(`tlm.searchSource.${store!.user.id}`); return sources.some(([id]) => id === value) ? value as Source : "catalog"; } catch { return "catalog"; } }
