import type { Song } from "../../core/song.js";
import { formatTime, h, icon } from "../dom.js";
import { ACTIONS, on, store } from "../store.js";
import { navigate } from "../router.js";

export function mountSongListView(root: HTMLElement, kind: "favorites" | "recent"): void {
  const title = kind === "favorites" ? "Favorites" : "Recently played";
  const page = h("section", { class: "simple-list song-list-page" }); const app = store!;
  function render(): void { const songs = kind === "favorites" ? app.data.getFavorites() : app.data.getRecent(); const rows = h("div", { class: "saved-song-list" }); songs.forEach((song, index) => rows.append(row(song, index))); page.replaceChildren(h("header", { class: "view-heading" }, h("div", {}, h("span", { class: "eyebrow mono-label" }, "YOUR MUSIC"), h("h1", {}, title), h("p", {}, `${songs.length} ${songs.length === 1 ? "song" : "songs"}`))), songs.length ? rows : h("div", { class: "empty-state" }, icon(kind === "favorites" ? "heart" : "play", 26), h("h2", {}, kind === "favorites" ? "Your favorites will live here" : "Your recent listening will appear here"), h("p", {}, kind === "favorites" ? "Tap the heart on any song to save it." : "Play a song and it will be easy to find again."), h("button", { type: "button", class: "gold-button", onClick: () => navigate("search") }, "Find music"))); }
  function row(song: Song, index: number): HTMLElement { const item = h("article", { class: "saved-song-row" }, h("span", { class: "row-position tabular-nums" }, String(index + 1).padStart(2, "0")), h("img", { src: song.artworkUrl || "assets/brand/app-icon.png", alt: "", width: 48, height: 48, loading: "lazy", decoding: "async" }), h("span", { class: "row-title" }, h("strong", {}, song.title), h("small", {}, song.artist ?? "Unknown artist")), h("span", { class: "source-badge" }, song.source ?? "Music"), h("span", { class: "row-duration tabular-nums" }, formatTime(song.duration ?? 0))); item.append(h("button", { type: "button", class: "icon-button", "aria-label": `Play ${song.title}`, onClick: () => { let node = app.library.getActiveList()?.head ?? null; while (node && node.value.id !== song.id) node = node.next; const target = node ?? ACTIONS.addLast(song); void ACTIONS.playNode(target); } }, icon("play", 18)), h("button", { type: "button", onClick: () => ACTIONS.addFirst(song) }, "Add first"), h("button", { type: "button", onClick: () => ACTIONS.addLast(song) }, "Add last")); if (kind === "favorites") item.append(h("button", { type: "button", class: "icon-button", "aria-label": `Remove ${song.title} from favorites`, onClick: () => ACTIONS.toggleFavorite(song) }, icon("heart-filled", 18))); return item; }
  root.replaceChildren(page); render(); on(kind === "favorites" ? "favorites" : "recent", render);
}
