import type { Song } from "../../core/song.js";
import { activeLineIndex, fetchLyrics } from "../../services/lyrics.js";
import { h } from "../dom.js";
import { on, store } from "../store.js";

export function mountLyricsPanel(): HTMLElement {
  const root = h("section", { class: "lyrics-panel", "aria-label": "Lyrics" }); let controller: AbortController | null = null; let songId = ""; let lines: { time: number; text: string }[] = []; let active = -2; let manualScroll = 0;
  const load = async (): Promise<void> => { const song = store?.player.current?.value; if (!song || song.id === songId) return; songId = song.id; controller?.abort(); controller = new AbortController(); root.replaceChildren(h("p", { class: "lyrics-message" }, "Finding lyrics…")); try { const result = await fetchLyrics(song, controller.signal); if (controller.signal.aborted) return; if (!result) root.replaceChildren(h("p", { class: "lyrics-message" }, "No lyrics found for this song.")); else if (result.instrumental) root.replaceChildren(h("p", { class: "lyrics-message" }, "Instrumental")); else if (result.synced?.length) { lines = result.synced; active = -2; const list = h("div", { class: "lyrics-lines" }); lines.forEach((line, index) => list.append(h("button", { type: "button", class: "lyrics-line", dataset: { index: String(index) }, onClick: () => store?.controller.seek(line.time) }, line.text))); list.addEventListener("scroll", () => { manualScroll = Date.now(); }, { passive: true }); root.replaceChildren(list, h("small", { class: "lyrics-credit" }, "Lyrics by LRCLIB")); sync(); } else if (result.plain) root.replaceChildren(h("p", { class: "plain-lyrics" }, result.plain), h("small", { class: "lyrics-credit" }, "Lyrics by LRCLIB")); else root.replaceChildren(h("p", { class: "lyrics-message" }, "No lyrics found for this song.")); } catch { if (!controller.signal.aborted) root.replaceChildren(h("p", { class: "lyrics-message" }, "Lyrics could not be loaded.")); } };
  const sync = (): void => { if (!lines.length) return; const index = activeLineIndex(lines, store?.controller.currentTime ?? 0); if (index === active) return; active = index; const list = root.querySelector<HTMLElement>(".lyrics-lines"); if (!list) return; list.querySelectorAll(".lyrics-line").forEach((line, i) => { line.classList.toggle("is-active", i === index); }); const activeElement = list.querySelector<HTMLElement>(`.lyrics-line[data-index="${index}"]`); if (activeElement && Date.now() - manualScroll > 4000) list.scrollTo({ top: activeElement.offsetTop - list.clientHeight * .35, behavior: "smooth" }); };
  on("playback", () => { void load(); }); on("time", sync); void load(); return root;
}
