import { formatTime, h, icon } from "../dom.js";
import { ACTIONS, on, store } from "../store.js";

export function mountPlayerDock(toggleNowPlaying: () => void): HTMLElement {
  const app = store!; const song = () => app.player.current?.value; const cover = h("img", { class: "dock-cover", src: "assets/brand/app-icon.png", alt: "", width: 52, height: 52 }); const title = h("strong", { class: "dock-title" }, "Choose a song"); const artist = h("small", { class: "dock-artist" }, "Tony Luk Music"); const source = h("span", { class: "source-badge" }, "Local");
  const favorite = h("button", { type: "button", class: "icon-button", "aria-label": "Favorite current song", onClick: () => { const current = song(); if (current) ACTIONS.toggleFavorite(current); } }, icon("heart", 19));
  const shuffle = h("button", { type: "button", class: "icon-button", "aria-label": "Shuffle", "aria-pressed": String(app.player.shuffle), onClick: () => ACTIONS.toggleShuffle() }, icon("shuffle", 19));
  const prev = h("button", { type: "button", class: "icon-button", "aria-label": "Previous", onClick: () => { void ACTIONS.prev(); } }, icon("prev", 20)); const play = h("button", { type: "button", class: "dock-play", "aria-label": "Play", onClick: () => { void ACTIONS.togglePlay(); } }, icon("play", 22)); const next = h("button", { type: "button", class: "icon-button", "aria-label": "Next", onClick: () => { void ACTIONS.next(); } }, icon("next", 20));
  const repeat = h("button", { type: "button", class: "icon-button", "aria-label": "Repeat off", onClick: () => { const mode = ACTIONS.cycleRepeat(); repeat.setAttribute("aria-label", `Repeat ${mode}`); repeat.setAttribute("aria-pressed", String(mode !== "off")); repeat.replaceChildren(icon(mode === "one" ? "repeat-one" : "repeat", 19)); } }, icon("repeat", 19));
  const elapsed = h("span", { class: "tabular-nums" }, "0:00"); const duration = h("span", { class: "tabular-nums" }, "0:00"); const range = h("input", { type: "range", min: 0, max: 100, value: 0, "aria-label": "Seek" }); range.addEventListener("input", () => { const total = app.controller.duration; if (!(total > 0)) return; const seconds = Number(range.value); range.style.setProperty("--fill", `${seconds / total * 100}%`); ACTIONS.seek(seconds); });
  const progress = h("div", { class: "dock-progress" }, elapsed, range, duration);
  const controls = h("div", { class: "dock-controls" }, shuffle, prev, play, next, repeat, progress);
  const lyrics = h("button", { type: "button", class: "icon-button", "aria-label": "Lyrics", onClick: toggleNowPlaying }, icon("lyrics", 19)); const chain = h("button", { type: "button", class: "icon-button", "aria-label": "The Chain", onClick: toggleNowPlaying }, icon("chain", 19)); const mute = h("button", { type: "button", class: "icon-button", "aria-label": "Mute", title: app.controller.supportsVolume ? "Mute" : "Volume is controlled inside Spotify", onClick: () => ACTIONS.toggleMute() }, icon("volume", 19)); const volume = h("input", { type: "range", min: 0, max: 1, step: .01, value: app.data.getPrefs().volume, disabled: !app.controller.supportsVolume, "aria-label": "Volume", title: app.controller.supportsVolume ? "Volume" : "Volume is controlled inside Spotify", onInput: (event: Event) => ACTIONS.setVolume(Number((event.currentTarget as HTMLInputElement).value)) });
  const dock = h("section", { class: "player-dock", "aria-label": "Player controls" }, h("button", { type: "button", class: "dock-track", onClick: toggleNowPlaying }, cover, h("span", { class: "dock-copy" }, title, artist, source), favorite), controls, h("div", { class: "dock-right" }, lyrics, chain, mute, volume));
  const update = (): void => { const current = song(); title.textContent = current?.title ?? "Choose a song"; artist.textContent = current?.artist ?? "Tony Luk Music"; cover.src = current?.artworkUrl || "assets/brand/app-icon.png"; source.textContent = current?.source === "itunes" ? "Preview 30s" : current?.source === "youtube" ? "YouTube" : current?.source === "spotify" ? "Spotify" : current?.source === "local" ? "Local" : "CC"; play.setAttribute("aria-label", app.playbackState === "playing" ? "Pause" : "Play"); play.replaceChildren(icon(app.playbackState === "playing" ? "pause" : "play", 22)); play.classList.toggle("is-loading", app.playbackState === "loading" || app.playbackState === "buffering"); volume.disabled = !app.controller.supportsVolume; mute.title = app.controller.supportsVolume ? "Mute" : "Volume is controlled inside Spotify"; if ("mediaSession" in navigator && typeof MediaMetadata !== "undefined" && current) navigator.mediaSession.metadata = new MediaMetadata({ title: current.title, artist: current.artist ?? "Unknown artist", album: current.album ?? "", artwork: current.artworkUrl ? [{ src: current.artworkUrl }] : [] }); };
  on("playback", update); // Engines report time a few times per second; requestAnimationFrame interpolates between
  // reports so the progress bar moves smoothly at 60fps. The loop stops while paused or hidden.
  let lastTime = 0, lastStamp = 0, frame = 0;
  const paint = (time: number): void => { const total = app.controller.duration; const safe = Number.isFinite(total) && total > 0 ? Math.min(time, total) : 0; if (!range.matches(":active")) { range.value = String(safe); range.style.setProperty("--fill", `${total > 0 ? safe / total * 100 : 0}%`); } elapsed.textContent = formatTime(safe); };
  const tick = (): void => { frame = 0; if (app.controller.paused || document.visibilityState === "hidden") return; paint(lastTime + (performance.now() - lastStamp) / 1000); frame = requestAnimationFrame(tick); };
  on("time", () => { const total = app.controller.duration; lastTime = app.controller.currentTime; lastStamp = performance.now(); duration.textContent = formatTime(total); range.max = String(total > 0 ? total : 100); paint(lastTime); if (!frame && !app.controller.paused) frame = requestAnimationFrame(tick); }); on("prefs", () => { shuffle.setAttribute("aria-pressed", String(app.player.shuffle)); repeat.setAttribute("aria-label", `Repeat ${app.player.repeat}`); repeat.setAttribute("aria-pressed", String(app.player.repeat !== "off")); repeat.replaceChildren(icon(app.player.repeat === "one" ? "repeat-one" : "repeat", 19)); }); update();
  document.addEventListener("keydown", event => { const target = event.target; if (target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement || (target instanceof HTMLElement && target.isContentEditable)) return; if (event.code === "Space") { event.preventDefault(); void ACTIONS.togglePlay(); } else if (event.shiftKey && event.key === "ArrowRight") void ACTIONS.next(); else if (event.shiftKey && event.key === "ArrowLeft") void ACTIONS.prev(); else if (event.key === "ArrowRight") ACTIONS.seek(app.controller.currentTime + 5); else if (event.key === "ArrowLeft") ACTIONS.seek(Math.max(0, app.controller.currentTime - 5)); else if (event.key.toLowerCase() === "m") ACTIONS.toggleMute(); else if (event.key.toLowerCase() === "s") ACTIONS.toggleShuffle(); else if (event.key.toLowerCase() === "r") ACTIONS.cycleRepeat(); else if (event.key.toLowerCase() === "l") toggleNowPlaying(); });
  if ("mediaSession" in navigator) { navigator.mediaSession.setActionHandler("play", () => { void ACTIONS.togglePlay(); }); navigator.mediaSession.setActionHandler("pause", () => { void ACTIONS.togglePlay(); }); navigator.mediaSession.setActionHandler("nexttrack", () => { void ACTIONS.next(); }); navigator.mediaSession.setActionHandler("previoustrack", () => { void ACTIONS.prev(); }); navigator.mediaSession.setActionHandler("seekto", details => { if (details.seekTime !== undefined) ACTIONS.seek(details.seekTime); }); }
  return dock;
}
